language: scala
jdk: oraclejdk8

scala:
      - 2.12.1

script:
  - sbt ++2.12.1 test
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
