language: scala
dist: trusty

scala:
      - 2.12.3

script:
  - sbt ++2.12.1 clean coverage test coverageReport
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

after_success:
  - bash <(curl -s https://codecov.io/bash)
